name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    env:
      repository_name: ${{ github.event.repository.name }}

    defaults:
      run:
        working-directory: /srv

    steps:
      - run: DATE=$(date +"%m-%d-%y")
      - run: sudo rm -rf $repository_name
      - run: sudo git clone https://github.com/VeroXyle/$repository_name.git

      - run: cd /srv/$repository_name && sudo npm i

      - run: sudo rm -rf /srv/$repository_name-production && sudo cp -r /srv/$repository_name /srv/$repository_name-production && echo $DATE
