name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    env:
      repository_name: ${{ github.event.repository.name }}

    defaults:
      run:
        working-directory: /srv

    steps:
      - run: mkdir -p ${{ github.event.repository.name }}

      - run: npm init -y
