name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    env:
      repository_name: ${{ github.event.repository.name }}

    defaults:
      run:
        working-directory: /srv

    steps:
      - run: sudo rm -rf ${{ github.event.repository.name }}
      - run: sudo git clone https://github.com/VeroXyle/${{ github.event.repository.name }}.git
      - run: cd /srv/${{ github.event.repository.name }}
      - run: ls
      - run: sudo npm i
