name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    env:
      user_name: veroxyle
      repository_name: ${{ github.event.repository.name }}

    defaults:
      run:
        working-directory: /srv

    steps:
      - run: sudo rm -rf $repository_name
      - run: sudo gh repo clone $user_name/$repository_name
      - run: cd /srv/$repository_name && sudo npm i
      - run: sudo rsync -r /srv/$repository_name /srv/$repository_name-prod
